#pragma once

#pragma comment(lib,"AppFrame.lib")

#include "DxLib.h"
#include "Application/ApplicationBase.h"
#include "CFile/CFile.h"
#include "Input/InputManager.h"
#include "Sound/SoundManager.h"
#include "AppFrameMath.h"
#include "Object/ObjectBase.h"
#include "Object/ComponentBase.h"
#include "Object/MV1Component.h"
#include "Object/AABB2DComponent.h"
#include "Object/CollisionComponent.h"
#include "Object/ObjectServer.h"
#include "Resource/ImageServer.h"
#include "Resource/ModelServer.h"
#include "Resource/FontServer.h"
#include "Resource/SoundServer.h"
#include "Resource/SoundServer.h"
#include "Utility/AABB2D.h"
#include "Utility/CharacterCodeConvert.h"
#include "Utility/ShiftJISChecker.h"
#include "Mode/ModeServer.h"